title: This is our Code Club podcast — leader guide
hero_image: images/banner.png
description: Use NotebookLM to turn your creators' writing about your Code Club into a cool and professional-sounding AI-generated podcast!
pdf: resources/LLM Storytime_leader.pdf
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: What you will do
  - title: Support creator writing
    completion:
      - engaged
  - title: Use NotebookLM
    completion:
      - internal
  - title: Unplugged activity — LLM storytime
  - title: Share your podcast
    completion:
      - external
